apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: bs3s65rhc-nodejs 
  janus-idp.io/tekton: bs3s65rhc-nodejs
  backstage.io/kubernetes-id: bs3s65rhc-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: bs3s65rhc-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml