apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: bs3s65rhc-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-nodejs:b983ec42af1a7235fc655d441df13eabe27cfff9@sha256:350c9cdbf5ee5b3672f9ba98f06bd2fe25163cde06bf99b891cab3cb0ce746c2
          name: container-image
